

services:
  frontend:
    build:
      context: ./frontend/cash-caddy-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend/src/CashCaddy
      dockerfile: Dockerfile
    ports:
      - "5000:8080"